### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by ilia-semenov** [Nildeala/nildeala.fr#1]
Hi William!

I wonder if you are open to sharing your Jekyll blog style with anyone. It looks really awesome, so I was wondering if I could adopt some ideas.

Thank you.

Ilia

**Comment by nileane** [comment]
Hey!

Thank you for your kind words. Feel free to adopt anything you like :). It's all free and open!

**Comment by nileane** [comment]
Hi there,

My Jekyll blog is now under the MIT License https://github.com/Nildeala/nildeala.fr/commit/54ee6f125fd5c769bfb7d46dcbb4a5f3e3dc9b38
