### ISSUE TITLE
Night mode is missing

### ISSUE THREAD

**Issue by younishd** [Nildeala/nildeala.fr#4]
Night mode is missing.

Chromium Version 68.0.3440.106 (Official Build) Arch Linux (64-bit)

**Comment by ghost** [comment]
:+1: we absolutely need night mode !

**Comment by nileane** [comment]
Dark mode is temporarily discontinued. https://github.com/Nildeala/nileane.fr/commit/6543d10ba19f98add526ace0c43a8ef25247d9b5
